---
title: "MAT1856/APM466 Assignment 1"
output:
  pdf_document: default
  html_notebook: default
---


```{r}
##import the data set of selected 10 bonds
library(readxl)
library(dplyr)
library(tidyr)
data <- read_excel("/Users/beibeigood/Desktop/apm466.xlsx",sheet = 1)
data
```


```{r}
##
data <- subset(data, select = -c(Name,ISIN,issue))
data$maturity = as.Date(data$maturity, format =  "%m/%d/%Y")
data = data %>%
  pivot_longer(!id & !maturity & !coupon & !last_coupon, names_to = "today", values_to = "price") %>%
  mutate(today = as.Date(today, format =  "%m/%d/%Y")) %>%
  mutate(last_coupon = as.Date(last_coupon, format =  "%m/%d/%Y")) %>%
  mutate(num_days = as.integer(difftime(today, last_coupon))) %>%
  mutate(price = price + (num_days/365)*coupon) %>%
  mutate(payment = 0.5 * coupon) %>%
  mutate(maturity_in_num_years = as.numeric(difftime(maturity,today))/365)  %>%
  mutate(N = floor(as.numeric(difftime(maturity,today))/(180))+1) %>%
  mutate(next_payment = last_coupon + 182) %>%
  mutate(t1 = as.integer(difftime(next_payment,today))/365)
```


```{r}
##write function to solve ytm
ytm <- function(row) {
       t <- seq(as.numeric(row['t1']), by= 0.5,length.out = as.numeric(row['N']))
       #print(t)
       #print(N)
       #print(as.numeric(row["payment"]))
       #print(as.numeric(row["price"]))
       r = uniroot(function(x) as.numeric(row["price"])-sum(as.numeric(row["payment"]) * exp(-x * t)) - 100 * exp(-x * t[as.numeric(row['N'])]),c(0,1))$root
}
yield_to_maturity = apply(data, MARGIN = 1, ytm)
```


```{r}
data = data %>%
  mutate(ytm = yield_to_maturity)
data
```

```{r}
library(ggplot2)
ytm_curve <-ggplot(data = data) + 
  geom_point(mapping = aes(x = maturity_in_num_years, y = ytm, color = as.factor(today))) +
  geom_smooth(mapping = aes(x = maturity_in_num_years, y = ytm, color = as.factor(today)),span = 0.2)+
  xlab("Time(time to maturity)") + 
  ylab("yield to maturity")
ytm_curve
```


```{r}
# Calculate the spot rate each day t
today <- unique(data$today)
subsets <-split(data,data$today)
subsets 
```


```{r}
##spot rate
spot_function <- function(data){
rate_vector = c()
for (id in 1:11) {
  if (id == 1){
    r1 = as.numeric(data[id,]['ytm'])
    rate_vector = c(r1)
    }
  if (id != 1){
    sum = 0
    t <- seq(as.numeric(data[id,]['t1']), by= 0.5,length.out = as.numeric(data[id,]['N'])+1)
    for (i in 1:((as.numeric(data[id,]['N']) -1) )) { 
     sum = sum + as.numeric(data[id,]["payment"])*exp(-t[i]*rate_vector[i])
    }
    new_spot_rate = uniroot(
    function(x) as.numeric(data[id,]["price"])-sum -(100 + as.numeric(data[id,]["payment"])) * exp(-x * t[as.numeric(data[id,]['N'])]), c(0,1))$root
rate_vector= c(rate_vector,new_spot_rate)
  }
}
data <- data %>%
  mutate(spot_rate = rate_vector)
}
```


```{r}
sum = 0
a=subsets$`2022-01-10`
r1 = as.numeric(a[1,]['ytm'])
rate_vector = c(r1)
t <- seq(as.numeric(a[2,]['t1']), by= 0.5,length.out = as.numeric(data[2,]['N'])+1)
for (i in 1:((as.numeric(a[2,]['N']) -1) )){
  sum = sum + as.numeric(a[2,]["payment"])*exp(-t[i]*rate_vector[i])
  sum
}
new_spot_rate = uniroot(
    function(x) as.numeric(a[2,]["price"])-sum -(100 + as.numeric(a[2,]["payment"])) * exp(-x * t[as.numeric(a[2,]['N'])]), c(-3,3))$root
new_spot_rate
```


```{r}
subsets$`2022-01-10`<-spot_function(subsets$`2022-01-10`)
subsets$`2022-01-11`<-spot_function(subsets$`2022-01-11`)
subsets$`2022-01-12`<-spot_function(subsets$`2022-01-12`)
subsets$`2022-01-13`<-spot_function(subsets$`2022-01-13`)
subsets$`2022-01-14`<-spot_function(subsets$`2022-01-14`)
subsets$`2022-01-17`<-spot_function(subsets$`2022-01-17`)
subsets$`2022-01-18`<-spot_function(subsets$`2022-01-18`)
subsets$`2022-01-19`<-spot_function(subsets$`2022-01-19`)
subsets$`2022-01-20`<-spot_function(subsets$`2022-01-20`)
subsets$`2022-01-21`<-spot_function(subsets$`2022-01-21`)
subsets$`2022-01-24`<-spot_function(subsets$`2022-01-24`)
```


```{r}
data_spot <- do.call(rbind, subsets)
data_spot
```

```{r}
##plot the spot curve
spot_curve<-ggplot(data = data_spot) + 
  geom_point(mapping = aes(x = maturity_in_num_years, y = spot_rate, color = as.factor(today))) +
  geom_smooth(mapping = aes(x = maturity_in_num_years, y = spot_rate, color = as.factor(today)),span = 0.2)+
  xlab("Time") + 
  ylab("Spot rate")
spot_curve
```

```{r}
rate_vector = c(as.numeric(set1[1,]['ytm']),0.008179258,0.009883582,0.01084055, 0.01222076)
t <- seq(as.numeric(set1[5,]['t1']), by= 0.5,length.out = as.numeric(set1[5,]['N']))
sum = as.numeric(set1[5,]["payment"])*exp(-t[1]*rate_vector[1]) + as.numeric(set1[5,]["payment"])*exp(-t[2]*rate_vector[2]) + as.numeric(set1[5,]["payment"])*exp(-t[3]*rate_vector[3])+ as.numeric(set1[5,]["payment"])*exp(-t[4]*rate_vector[4])
print(sum)
new_spot_rate = uniroot(
    function(x) as.numeric(set1[5,]["price"])-sum -(100+as.numeric(set1[5,]["payment"])) * exp(-x *t[as.numeric(set1[5,]['N'])]), c(-3,3))$root
new_spot_rate
```

```{r}
#calculate the forward rate for each bond i at each da
##interpolate to get the spot rate for 1,2,3,4,5 yr
data_from_spot <- ggplot_build(spot_curve)$data[2][[1]][,c(1,2,3)]
data_from_spot
```

```{r}
spot_filtered <- data_from_spot  %>%
  filter(abs(x-1)<0.03 |abs(x-2)<0.032|abs(x-3)<0.032|abs(x-4)<0.0318|abs(x-5)<0.0318) %>%
  mutate(today = rep(today, each=5)) %>%
  mutate(num_year= rep(1:5,times=11))
spot_filtered
```

```{r}
spot_filtered_subset <- split(spot_filtered, spot_filtered$today)
spot_filtered_subset
```

```{r}
get_forward_rate <-function(data){
  spot_rate_i <- as.numeric(data[,3])
  forward_rate_i <-c()
  for (j in 1:4) {
    f_1_j = (spot_rate_i[j+1]*(j+1)-(spot_rate_i[1]))/j
    forward_rate_i <- append(forward_rate_i,f_1_j)
  }
  forward_rate_i
}
```

```{r}
f10 <- get_forward_rate(spot_filtered_subset$`2022-01-10`)
f11 <- get_forward_rate(spot_filtered_subset$`2022-01-11`)
f12 <- get_forward_rate(spot_filtered_subset$`2022-01-12`)
f13 <- get_forward_rate(spot_filtered_subset$`2022-01-13`)
f14 <- get_forward_rate(spot_filtered_subset$`2022-01-14`)
f17 <- get_forward_rate(spot_filtered_subset$`2022-01-17`)
f18 <- get_forward_rate(spot_filtered_subset$`2022-01-18`)
f19 <- get_forward_rate(spot_filtered_subset$`2022-01-19`)
f20 <- get_forward_rate(spot_filtered_subset$`2022-01-20`)
f21 <- get_forward_rate(spot_filtered_subset$`2022-01-21`)
f24 <- get_forward_rate(spot_filtered_subset$`2022-01-24`)
```



```{r}
forward_rates_col = c(f10,f11,f12,f13,f14,f17,f18,f19,f20,f21,f24)
today_forward = rep(today,each=4)
forward_num = rep(1:4,times =11)
forward_data_plot <- data_frame(forward_rates_col,today_forward,forward_num)
```

```{r}
plot(x = forward_data_plot$forward_num, y = forward_data_plot$forward_rates_col,main = "approx(.) and approxfun(.)")
points(approx(forward_data_plot$forward_num, forward_data_plot$forward_rates_col), col = 2, pch = "*")
#points(approx(x, y, method = "constant"), col = 4, pch = "*")

```

```{r}
##plot the forward curve
forward_curve<-ggplot(data = forward_data_plot) + 
  geom_point(mapping = aes(x = forward_num, y = forward_rates_col, color = as.factor(today_forward))) +
  geom_smooth(mapping = aes(x = forward_num, y = forward_rates_col, color = as.factor(today_forward)),span = 0.5)+
  xlab("1 year-x year") + 
  ylab("Forward rate") +
  scale_fill_discrete(name = "Date")
forward_curve
```

question 5
```{r}
data_from_ytm <- ggplot_build(ytm_curve)$data[2][[1]][,c(1,2,3)]
```

```{r}
ytm_filtered <- data_from_ytm  %>%
  filter(abs(x-1)<0.03 |abs(x-2)<0.032|abs(x-3)<0.032|abs(x-4)<0.0318|abs(x-5)<0.0318) %>%
  mutate(today = rep(today, each=5)) %>%
  mutate(num_year= rep(1:5,times=11))
ytm_filtered
```

```{r}
ytm_filtered_subset <- split(ytm_filtered, ytm_filtered$num_year)
```

```{r}
get_random_variable <-function(data){
  x_i <-c()
  for (j in 1:9) {
    xij = log(as.numeric(data[j+1,3])/as.numeric(data[j,3]))
    x_i <- append(x_i,xij)
  }
  x_i
}
```

```{r}
x1 = get_random_variable(ytm_filtered_subset$`1`)
x2 = get_random_variable(ytm_filtered_subset$`2`)
x3 = get_random_variable(ytm_filtered_subset$`3`)
x4 = get_random_variable(ytm_filtered_subset$`4`)
x5 = get_random_variable(ytm_filtered_subset$`5`)
X_yield <- data.frame(x1,x2,x3,x4,x5)
cov_yield = cov(X_yield)
cov_yield
```

```{r}
forward_data_plot_subsets <- split(forward_data_plot,forward_data_plot$forward_num)
forward_data_plot_subsets
```

```{r}
get_random_variable2 <-function(data){
  x_i <-c()
  for (j in 1:9) {
    xij = log(as.numeric(data[j+1,1])/as.numeric(data[j,1]))
    x_i <- append(x_i,xij)
  }
  x_i
}
```

```{r}
x11 = get_random_variable2(forward_data_plot_subsets$`1`)
x12 = get_random_variable2(forward_data_plot_subsets$`2`)
x13 = get_random_variable2(forward_data_plot_subsets$`3`)
x14 = get_random_variable2(forward_data_plot_subsets$`4`)
X_forward <- data.frame(x11,x12,x13,x14)
cov_forward= cov(X_forward)
cov_forward
```

```{r}
eigen_space_ytm = eigen(cov_yield) 
eigen_space_ytm$values
eigen_space_ytm$vectors
```

```{r}
eigen_space_forward = eigen(cov_forward) 
eigen_space_forward$values
eigen_space_forward$vectors
```
